#define MKind(index)@ flags[7100+index-1] @
#define MMaxHP(index)@ flags[7105+index-1] @
#define MHP(index)@ flags[7110+index-1] @
#define MMP(index)@ flags[7115+index-1] @
#define MHit(index)@ flags[7120+index-1] @
#define MDod(index)@ flags[7125+index-1] @
#define MMag(index)@ flags[7130+index-1] @
#define MMgr(index)@ flags[7135+index-1] @
#define MRea(index)@ flags[7140+index-1] @
#define MMbl(index)@ flags[7145+index-1] @
#define MFer(index)@ flags[7150+index-1] @
#define MAtk(index)@ flags[7155+index-1] @
#define MDef(index)@ flags[7160+index-1] @
#define MXP(index)@ flags[7165+index-1] @
#define MGP(index)@ flags[7170+index-1] @

#define PHit(index)@ flags[7175+index-1] @
#define PDod(index)@ flags[7180+index-1] @
#define PMag(index)@ flags[7185+index-1] @
#define PMgr(index)@ flags[7190+index-1] @
#define PRea(index)@ flags[7195+index-1] @
#define PMbl(index)@ flags[7200+index-1] @
#define PFer(index)@ flags[7205+index-1] @
#define PAtk(index)@ flags[7210+index-1] @
#define PDef(index)@ flags[7215+index-1] @

#define Time(index)@ Flags[7220+index-1] @
#define MTime(index)@ Flags[7225+index-1] @
#define RetVal@ Flags[7230] @
#define WepnSound@ Flags[7231] @
#define MaxSpeed@ Flags[7232] @

#define Main@ 1 @
#define CharTurn@ 2 @
#define CharAtk@ 3 @
#define SpellMenu@ 4 @
#define ItmMenu@ 5 @
#define MonTurn@ 6 @
#define MonAtk@ 7 @
#define ChooseEnemy@ 8 @
#define ChooseChar@ 9 @
#define EnemyDie@ 10 @
#define DrawStat@ 11 @
#define DrawTimeBars@ 12 @
#define SetUpScr@ 13 @
#define Numbers@ 14 @
#define SetupEnemies@ 15 @
#define MakeEnemy@ 16 @
#define MakeMonStats@ 17 @
#define LoadWeapon@ 18 @
#define Defeated@ 19 @
#define EnemyMove@ 41 @
#define DoFirst@ 42 @

#define BatFX(num)@ 19+num @
